export type InternFull = {
  id: number;
  nickname: string;
  department: number;
  grade: number;
  labo: string | null;
  club: string | null;
  achievements: string | null;
  experience: string | null;
  company_name: string | null;
  intern_detail: string;
  work_duration_description: string | null;
  weekly_hours_description: string | null;
  hourly_wage_description: string | null;
  work_style: string | null;
  application_reason: string | null;
  acquired_skill: string | null;
  appeal: string | null;
  advise: string | null;
  evaluation: number | null;
  evaluation_reason: string | null;
  intern_overview: string;
  catchphrase: string;
  hourly_wage: number | null;
  weekly_hours: number | null;
  work_duration: number | null;
  industry: number;
  occupation: number;
  recruitment_id: number | null;
  created_at: string;
  updated_at: string;
};
