Recruitment.create!([
  {
    title: '<実務未経験OK / エンジニア長期インターン> 研修制度・教育支援制度充実！自社プロダクトのWeb開発業務を"PM"として「設計から実装まで」',
    industry: 'WEB業界',
    description: 'Techouseの長期インターンでは、自社プロダクトのWeb開発業務を《設計から実装まで》お任せしております。業務外でも社内で〈週次勉強会〉〈ハッカソン〉〈LT会〉など高頻度で開催、インターンであっても利用できる〈福利厚生 / 学習支援制度〉を整備しており、エンジニアとして学習するための環境を全て整えています。アルバイトのようにシフト制での勤務となりますので、学業・研究との両立も問題ございません。現在のエンジニア組織は正社員に加え、50名以上のインターンが在籍しております。インターン全体の8割が大学院生、全体の7割が情報系専攻の学生という構成になっており、ハイレベルな環境で実務開発に取り組んでいただくことができます。24卒インターン参加者の就活実績として、AWS Irelandや日本IBM、アクセンチュアなど、大手IT・SIer企業様の内定をほとんどのメンバーがいただいております。その上で、Techouseに新卒入社予定のメンバーも多数在籍しております。',
    benefits: '約1か月間の研修を実施していただいた後、実務開発開始となります。プロダクト開発に携わっていただくための研修プログラムをご用意しておりますので、開発未経験の方でもご安心ください。',
    job_description: '業務例・ソフトウェアエンジニアとしての開発業務全般・サービスの要件定義/設計/開発/テスト/運用・顧客やメンバーへのヒアリングを通した問題発見・メンバーのマネジメント/メンタリング・技術調査/技術選定',
    job_titles: 'Webエンジニア（バックエンド/フロントエンド）',
    job_engineer: true,
    job_designer: false,
    job_sales: false,
    job_planning: false,
    job_marketing: false,
    job_writer: false,
    job_others: false,
    skills_acquired: 'フルスタックなWeb開発経験、PM経験',
    wage: 1200,
    salary_notes: '時給一律、初月のみ研修期間のため月３万円',
    work_location: '東京都港区三田3-13-12三田MTビル 5F',
    min_work_period: '最低6ヶ月',
    min_work_days: '週3日以上',
    min_work_hours: '1日3時間から (10:00~22:00の間)',
    commute_support: '月3万円まで',
    required_skills: 'プログラミング経験 ※言語・スキルレベルは問いません。授業で学んだ、独学で勉強したなどでもOK！',
    welcome_skills: 'Ruby, JavaScript, React などを用いたWEB開発経験',
    promotion_system: 'なし',
    remote_policy: 'フルリモート/一部リモート勤務',
    selection_flow: '面接 → 1ヶ月研修 → 採用',
    deadline: '2025年1月31日',
    welfare_benefits: '書籍購入自由・資格取得費用の会社負担・月100USDまで個人学習用途でAWSの自由利用可',
    apply_url: 'https://www.in-fra.jp/apply-internship/23630',
    company_id: @techouse,
    user_id: @shirasawa
  },
  {
    title: '【未経験も大歓迎】SaaS製品や社内教育コンテンツの動画編集アシスタントを募集!',
    industry: '受託開発事業、自社ソフトウェアの提供',
    description: 'クリエイティブなことが好き、AIみたいな新しい技術が好き。その興味や好奇心を仕事に活かしてみませんか？私たちの会社では、SaaS製品のマーケティングや社内教育の分野であなたの才能を発揮いただけます。国籍も経歴も様々なメンバーが集まったチームで新しいことに挑戦しましょう!どんなきっかけでも大歓迎です!【動画をつくりたい / 英語でコミュニケーションがとりたい / 企業で働くイメージをつけたい / マーケティングや新しいことを学びたい】',
    benefits: '曜日や時間が選べる / 服装自由 / 未経験歓迎 / スキルが身につく / 筑波大生履歴書不要 / 在宅勤務可能',
    job_description: '最先端のSaaSプロダクトを世界に届けるためのプロモーション動画の編集。プロダクトの紹介や使い方の解説、サービスの長所を印象付けるための機能性と視覚的魅力を融合させたショートムービーの企画・制作。社内の日本語教育コンテンツの動画編集。その他関連業務',
    job_titles: 'Marketing Specialist',
    job_engineer: false,
    job_designer: false,
    job_sales: false,
    job_planning: true,
    job_marketing: true,
    job_writer: false,
    job_others: false,
    skills_acquired: 'SEO, branding, communication',
    wage: 1100,
    salary_notes: '',
    work_location: '茨城県つくば市梅園2丁目1-13 筑波コウケンビル 3F',
    min_work_period: '',
    min_work_days: '週2回〜',
    min_work_hours: '1日3時間〜(9:00〜18:00)',
    commute_support: '',
    required_skills: '平日10時間以上勤務可能な方',
    welcome_skills: '未経験歓迎',
    promotion_system: '能力や責任範囲に対して評価および昇給制度があります。',
    remote_policy: '業務に習熟して、信頼関係が築けたタイミングで在宅勤務可能',
    selection_flow: '面接のみ',
    deadline: '2025-1-31',
    welfare_benefits: '社内にお菓子や飲み物を販売中!',
    apply_url: 'https://tsukubaito.azurewebsites.net/apply/vbimo/VeBuIn(%E5%8B%95%E7%94%BB)/VeBuIn%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE',
    company_id: @vebuin,
    user_id: @kawakami
  },
  {
    title: '【長期】新領域「お祝いテック」のエンジニアインターン募集！',
    industry: 'ブライダル業界のDX推進',
    description: '株式会社 TAIAN は「お祝いテックカンパニー」として、現在は主にブライダル業界の DX を推進する会社です。',
    benefits: '交通費支給（上限25,000円/月）、新卒選考希望の場合は早期内定に向けた選考も実施',
    job_description: 'バックエンド/フロントエンド/フルスタックに応じて、以下の業務をお任せします。\n- 結婚式準備〈toC、toB〉、見積もり・受発注〈toB〉\n- CRM、MA ツール〈toB〉など。\nエンジニアチームに所属して一緒にコードを書いて開発できます！',
    job_titles: 'フルスタックエンジニアインターン',
    job_engineer: true,
    job_designer: false,
    job_sales: false,
    job_planning: false,
    job_marketing: false,
    job_writer: false,
    job_others: false,
    skills_acquired: 'TypeScript、React、Ruby on Rails、Docker、AWS などの最新技術を用いた開発経験。エンジニアチームでの開発経験。',
    wage: 2000,
    salary_notes: '時給2,000円以上（面談にて決定）※開発未経験の方向けコースもあります。',
    work_location: '全日出社（慣れてきたタイミングで一部リモート可）',
    min_work_period: '3ヶ月以上',
    min_work_days: '平日で週20時間以上',
    min_work_hours: '1日あたりの勤務時間は応相談、週20時間以上',
    commute_support: '交通費支給（上限25,000円/月）',
    required_skills: '特になし',
    welcome_skills: 'Ruby on Rails や React/TypeScript を使用した開発経験',
    promotion_system: '新卒選考希望の場合は早期内定に向けた選考を実施',
    remote_policy: '全日出社（慣れてきたタイミングで一部リモート可）',
    selection_flow: 'カジュアル面談（30分）→ オンライン面接（60分）→ 1日就業体験（¥10,000）→ 就業開始',
    deadline: '',
    welfare_benefits: '',
    apply_url: '',
    company_id: @taian,
    user_id: @watanabe
  },
  {
    title: 'つくば初のスタートアップ企業で日本の観光を支えるLLM開発インターン生を募集中',
    industry: '観光業界、AI/LLM開発',
    description: 'ポッドテック株式会社はドメイン特化型のLLM構築やデータセット構築を主な事業としています。生成AIのフルスクラッチ開発や活用を推進してきたメンバーが揃っており、オーダーメイドな生成AI構築を得意としています。',
    benefits: '',
    job_description: 'LLM開発用の観光データセットを開発する学生インターン募集！観光LLM開発のためのデータ収集・整理・分類、およびLLMの品質向上のためのフィードバックを行います。',
    job_titles: 'LLM開発メンバー（学生インターン）',
    job_engineer: true,
    job_designer: false,
    job_sales: false,
    job_planning: false,
    job_marketing: false,
    job_writer: false,
    job_others: false,
    skills_acquired: 'データ分析、AI/LLM開発の知識、データセット構築の経験',
    wage: 1050,
    salary_notes: '要相談',
    work_location: '茨城',
    min_work_period: '要相談',
    min_work_days: '要相談',
    min_work_hours: '要相談',
    commute_support: '要相談',
    required_skills: 'データ収集・分析への関心、責任感を持ちプロジェクトに積極的に関われる方、観光分野への興味や知識、プログラミング（PythonやVBAなど）',
    welcome_skills: '要相談',
    promotion_system: '要相談',
    remote_policy: '要相談',
    selection_flow: '要相談',
    deadline: '要相談',
    welfare_benefits: '要相談',
    apply_url: '',
    company_id: @podtech,
    user_id: @ogawa
  },
  {
    title: "中高生を導く大学生プログラミング教育メンター募集中！",
    industry: "教育、IT・プログラミング教育",
    description: "ライフイズテックは国内実績No.1の中高生向けIT・プログラミング教育事業者です。",
    benefits: "デジタル＆クリエイティブスキル研修プログラムを無料で受講できる",
    job_description: "中高生向けIT・プログラミングキャンプ＆スクールで教え手（メンター）となり、子どもたちの未来を拡げる役割を担います。IT技術だけでなくデザインやファシリテーション等のスキルを学びます。",
    job_titles: "大学生メンター",
    job_engineer: true,
    job_designer: true,
    job_sales: false,
    job_planning: true,
    job_marketing: false,
    job_writer: false,
    job_others: false,
    skills_acquired: "IT技術、デザイン、ファシリテーション、チームビルディング、タスクマネジメントのスキルが習得できます",
    wage: 1200,
    salary_notes: "本研修プログラムは無償で提供されます。メンターとしての活動については別途説明があります",
    work_location: "関東または関西（対面研修あり）、一部オンライン",
    min_work_period: "2024年7月～8月に連続した5日間×2回以上、長期的にコミットできる方",
    min_work_days: "5日間×2回（計10日間）以上",
    min_work_hours: "1日あたり9:30～18:00（約8.5時間）",
    commute_support: "対面研修に参加する場合、交通費の一部を支給",
    required_skills: "大学生/大学院生/専門学生/高等専門学校生であること、自分のパソコンを持参できること",
    welcome_skills: "ITやプログラミング、デザイン等に興味がある方",
    promotion_system: "要相談",
    remote_policy: "研修はオンラインと対面の併用。対面研修は関東または関西で実施",
    selection_flow: "説明会 → 1次選考（グループ面接）→ 2次選考（作品審査）→ 研修 → 最終合格発表",
    deadline: "募集時期は不定期、プレエントリー受付中",
    welfare_benefits: "要相談",
    apply_url: "",
    company_id: @lifeistech,
    user_id: @kuwahara
  }
])
