# 既存のデータを削除
Recruitment.destroy_all # まずRecruitmentを削除して、Companyに関連する外部キー制約エラーを回避
Company.destroy_all

# 会社データとリクルートメントデータを含む配列を定義
companies = [
  {
    company_data: {
      name: '株式会社Techouse',
      description: 'Techouseは国内1,000万人以上が従事する製造業を中心に、アナログな産業をデジタル化する会社です。現在はトヨタ、ホンダ、デンソーなど国内を代表する企業が利用しており、サービスの利用ユーザーは年間500万人にも上ります。下記2事業を展開しておりますが、毎年新規サービスをリリースしており、次の社会インフラとしてふさわしいサービスプラットフォームに進化させ続けております。',
      website_url: 'https://jp.techouse.com/',
      logo_url: '',
      picture_url: '',
      location: '東京都港区三田3-13-12三田MTビル 5F',
      email: 'techouse@sample.com',
      phone_number: '123-456-7890',
      password: 'password1',
      password_confirmation: 'password1'
    },
    recruitment_data: {
      title: '<実務未経験OK / エンジニア長期インターン> 研修制度・教育支援制度充実！自社プロダクトのWeb開発業務を"PM"として「設計から実装まで」お任せします - 株式会社Techouseの長期・有給インターンシップ',
      industry: 'WEB業界',
      description: 'Techouseの長期インターンでは、自社プロダクトのWeb開発業務を《設計から実装まで》お任せしております。業務外でも社内で〈週次勉強会〉〈ハッカソン〉〈LT会〉など高頻度で開催、インターンであっても利用できる〈福利厚生 / 学習支援制度〉を整備しており、エンジニアとして学習するための環境を全て整えています。アルバイトのようにシフト制での勤務となりますので、学業・研究との両立も問題ございません。現在のエンジニア組織は正社員に加え、50名以上のインターンが在籍しております。インターン全体の8割が大学院生、全体の7割が情報系専攻の学生という構成になっており、ハイレベルな環境で実務開発に取り組んでいただくことができます。24卒インターン参加者の就活実績として、AWS Irelandや日本IBM、アクセンチュアなど、大手IT・SIer企業様の内定をほとんどのメンバーがいただいております。その上で、Techouseに新卒入社予定のメンバーも多数在籍しております。',
      benefits: '約1か月間の研修を実施していただいた後、実務開発開始となります。プロダクト開発に携わっていただくための研修プログラムをご用意しておりますので、開発未経験の方でもご安心ください。',
      job_description: '業務例・ソフトウェアエンジニアとしての開発業務全般・サービスの要件定義/設計/開発/テスト/運用・顧客やメンバーへのヒアリングを通した問題発見・メンバーのマネジメント/メンタリング・技術調査/技術選定',
      job_titles: 'Webエンジニア（バックエンド/フロントエンド）',
      job_engineer: true,
      job_designer: false,
      job_sales: false,
      job_planning: false,
      job_marketing: false,
      job_writer: false,
      job_others: false,
      skills_acquired: 'フルスタックなWeb開発経験、PM経験',
      wage: '時給: 1,200円',
      salary_notes: '時給一律、初月のみ研修期間のため月３万円',
      work_location: '東京都港区三田3-13-12三田MTビル 5F',
      min_work_period: '最低6ヶ月',
      min_work_days: '週3日以上',
      min_work_hours: '1日3時間から (10:00~22:00の間)',
      commute_support: '月3万円まで',
      required_skills: 'プログラミング経験 ※言語・スキルレベルは問いません。授業で学んだ、独学で勉強したなどでもOK！',
      welcome_skills: 'Ruby, JavaScript, React などを用いたWEB開発経験',
      promotion_system: 'なし',
      remote_policy: 'フルリモート/一部リモート勤務',
      selection_flow: '面接 → 1ヶ月研修 → 採用',
      deadline: '2025年1月31日',
      welfare_benefits: '書籍購入自由・資格取得費用の会社負担・月100USDまで個人学習用途でAWSの自由利用可',
      apply_url: 'https://www.in-fra.jp/apply-internship/23630'
    }
  },
  {
    company_data: {
      name: 'VeBuIn株式会社（ヴィビュイン株式会社）',
      description: 'VeBuInは、日本×インドのハイブリッド開発を行うIT企業です。経験豊富なインドのシステムエンジニアが先端IT技術を活用してシステム開発を実行。',
      website_url: 'https://vebuin.com/',
      logo_url: '',
      picture_url: '',
      location: '〒305-0045 茨城県つくば市梅園2-1-13 筑波コウケンビル',
      email: 'vebuin@sample.com',
      phone_number: '987-654-3210',
      password: 'password2',
      password_confirmation: 'password2'
    },
    recruitment_data: {
      title: '【未経験も大歓迎】SaaS製品や社内教育コンテンツの動画編集アシスタントを募集!',
      industry: '受託開発事業、自社ソフトウェアの提供',
      description: 'クリエイティブなことが好き、AIみたいな新しい技術が好き。その興味や好奇心を仕事に活かしてみませんか？私たちの会社では、SaaS製品のマーケティングや社内教育の分野であなたの才能を発揮いただけます。国籍も経歴も様々なメンバーが集まったチームで新しいことに挑戦しましょう!どんなきっかけでも大歓迎です!【動画をつくりたい / 英語でコミュニケーションがとりたい / 企業で働くイメージをつけたい / マーケティングや新しいことを学びたい】',
      benefits: '曜日や時間が選べる / 服装自由 / 未経験歓迎 / スキルが身につく / 筑波大生履歴書不要 / 在宅勤務可能',
      job_description: '最先端のSaaSプロダクトを世界に届けるためのプロモーション動画の編集。プロダクトの紹介や使い方の解説、サービスの長所を印象付けるための機能性と視覚的魅力を融合させたショートムービーの企画・制作。社内の日本語教育コンテンツの動画編集。その他関連業務',
      job_titles: 'Marketing Specialist',
      job_engineer: false,
      job_designer: false,
      job_sales: false,
      job_planning: true,
      job_marketing: true,
      job_writer: false,
      job_others: false,
      skills_acquired: 'SEO, branding, communication',
      wage: '時給: 1,100円',
      salary_notes: '',
      work_location: '茨城県つくば市梅園2丁目1-13 筑波コウケンビル 3F',
      min_work_period: '',
      min_work_days: '週2回〜',
      min_work_hours: '1日3時間〜(9:00〜18:00)',
      commute_support: '',
      required_skills: '平日10時間以上勤務可能な方',
      welcome_skills: '未経験歓迎',
      promotion_system: '能力や責任範囲に対して評価および昇給制度があります。',
      remote_policy: '業務に習熟して、信頼関係が築けたタイミングで在宅勤務可能',
      selection_flow: '面接のみ',
      deadline: '2025-1-31',
      welfare_benefits: '社内にお菓子や飲み物を販売中!',
      apply_url: 'https://tsukubaito.azurewebsites.net/apply/vbimo/VeBuIn(%E5%8B%95%E7%94%BB)/VeBuIn%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE'
    }
  },
  {
    company_data: {
      name: 'ルクール株式会社',
      description: '個別指導塾以上に1人1人にしっかりと向き合う集団指導塾です。',
      website_url: 'https://www.lecoeur-edu.com/',
      logo_url: '',
      picture_url: '',
      location: '千葉県柏市松葉町2丁目15番14号 松浦ビル2階',
      email: 'lecoeur-edu@sample.com',
      phone_number: '',
      password: 'password3',
      password_confirmation: 'password3'
    },
    recruitment_data: {
      title: '【インターン生大募集】学習塾の立ち上げに関われる特別バイト！',
      industry: '教育',
      description: 'ルクールのミッションは「想像を超える自分に出会うきっかけをつくる。」京大出身、人材業界で活躍した代表が立ち上げた新しい学習塾です。高校受験合格がゴールではなく、その先のキャリアをきちんと見据えたキャリア教育も融合しています。塾講師ではなく、一緒に学習塾の運営と事業拡大を目指すインターン生を大募集！教育業界に興味のある方、事業の立ち上げに関わりたい方、新しいスキルを身に付けたい方、どなたでも一度お問い合わせください。普通のアルバイトでは決して経験出来ない貴重な体験があなたを待っています。',
      benefits: '土日祝日のみでも可 / 曜日や時間が選べる / 服装自由 / スキルが身につく / 交通費支給',
      job_description: '集客に係るSNS運用 / 保護者対応や電話応対などの事務作業 / 企画・カリキュラム提案等',
      job_titles: 'インターン生（学習塾立上げ）',
      job_engineer: false,
      job_designer: false,
      job_sales: false,
      job_planning: true,
      job_marketing: true,
      job_writer: false,
      job_others: false,
      skills_acquired: '【創成期に関われる】学習塾の立ち上げフェーズに参加できます！\n京大出身の校舎長と一緒に学習塾の立ち上げフェーズに1から関われます。また、社外の超一流の方をお招きした特別授業・社会科見学なども実施予定。新規事業の創成期を働きながら目の当たりにできます!\n【SNS運用も積極的】広報スキルも身に付きます!\nインターン生としての採用なので塾講師の募集ではありません。運営側のSNS運用や広報企画にも参加いただき、教育業界の内側を経験出来ます!マーケティングスキルも習得しながら、あなたのアイデアや想いをぶつけてみてください^^\n【就活にも有利】代表からのサポートも受けられる!\nパーソルやビズリーチなどで就職支援、採用人事を行ってきた代表からのリアルなアドバイスも享受出来ます!あなたの望む業界・業種の情報を惜しみなくお伝えしますよ^^',
      wage: '時給: 1,050円',
      salary_notes: '生徒指導: 1,500円, 集団指導: 2,500円〜3,000円',
      work_location: '千葉県柏市松葉町2丁目15-14 松浦ビル2F',
      min_work_period: '',
      min_work_days: '週2回〜',
      min_work_hours: '1日3時間〜(9:00〜19:00)',
      commute_support: '交通費支給: 1万円まで(業務によっては、在宅勤務あり)',
      required_skills: '泥臭く、当事者意識を持って楽しめるスタンス！',
      welcome_skills: '',
      promotion_system: '昇給制度：あり（能力重視で上限なし）',
      remote_policy: '対面勤務',
      selection_flow: '履歴書提出 -> 面接',
      deadline: '2025-1-31',
      welfare_benefits: '・定期1on1 ・フリードリンク、フリースナック ・人生を豊かにする手当（グレードによる）',
      apply_url: 'https://tsukubaito.azurewebsites.net/apply/lec03/%E3%83%AB%E3%82%AF%E3%83%BC%E3%83%AB/%E9%AB%98%E6%A0%A1%E5%8F%97%E9%A8%93%E5%B0%82%E9%96%80%E5%A1%BE%E3%83%AB%E3%82%AF%E3%83%BC%E3%83%AB'
    }
  },
  {
    company_data: {
      name: '株式会社FREEDiVE',
      description: '弊社は、クライアントファーストを至上命題とするマーケティング企業です。徹底した仕組み化を実践している運用戦略設計と、それを実践する「人」の育成に重きをおいて広告主様ひいては社会に対しての課題解決を目指します。\nメンバーもクライアントもユーザーも関わる全ての人が「なりたい自分」になれるような事業を増やし、社会課題に価値を提供し続けていきます。',
      website_url: 'https://freedive.co.jp/',
      logo_url: '',
      picture_url: '',
      location: '〒305-0031 茨城県つくば市吾妻1-7-1トナリエクレオつくば5F-C5030',
      email: 'freedive@sample.com',
      phone_number: '',
      password: 'password4',
      password_confirmation: 'password4'
    },
    recruitment_data: {
      title: '【成長体験】マーケ力・事業想像力を身につけたい筑波大インターン生WANTED!',
      industry: 'マーケティング / 物流 / 業務改善DX',
      description: 'FREEDiVEはつくばに拠点を置く8期目のベンチャー企業です。筑波大学のアルバイトインターン/卒業生も含め、多様なバックグラウンドを持つメンバーが集い、4年連続で「ベストベンチャー100」を受賞しました。私たちの特長は、マーケティングノウハウに裏打ちされた「顧客の未来を科学する」アプローチ。データを用いた課題解決を駆使して、常に業界の一歩先を行く戦略を展開しています。3年後の上場に向けて、共に成長していく仲間を募集中です！少しでも興味があれば、ぜひお越しください！',
      benefits: '曜日や時間が選べる / 服装自由 / 未経験歓迎 / 経験者優遇 / スキルが身につく / 筑波大生履歴書不要',
      job_description: '事業運営サポート担当: モバイル事業におけるカスタマーサクセスや数値分析、DX業務等',
      job_titles: '事業運営サポート担当',
      job_engineer: false,
      job_designer: false,
      job_sales: false,
      job_planning: true,
      job_marketing: true,
      job_writer: false,
      job_others: false,
      skills_acquired: '【限定募集】マーケティング・物流・業務改善DXまで多岐に渡ります。\n皆様の希望や面談時の適正に合わせて多種多様なお仕事を経験できます。toCのインバウンド営業やコール業務、企画設計やマーケ、そして業務改善・DX化を進める仕事などがあります。もちろん簡単な軽作業からでもOKです!\n【筑波大生多数所属】過去の経験は問いません！まずは面談からフランクに話しましょう\n筑波大生はインターン/アルバイト含め25名以上在籍!来年卒業を迎える方もいる為、採用強化中です。まずは将来やりたい事や大学生活をお聞きし、当社の説明を聞いていただいた上でマッチすれば面接に進みましょう!\n【時給1200円〜】高時給で様々な経験を得られる良質な長期インターン!\n基本的には週12時間以上の出社を原則としております。もちろん昇給制度もありますので、行う仕事内容や成果に合わせて稼げる!そして社会人に向けての圧倒的な経験を積むことができます。限定10名程度を募集しますよ!',
      wage: '時給: 1,200円',
      salary_notes: '',
      work_location: '茨城県つくば市吾妻1丁目7-1トナリエクレオつくば5F C5030',
      min_work_period: '',
      min_work_days: '週2回〜',
      min_work_hours: '1日あたりの勤務時間は応相談(10:00〜19:00)',
      commute_support: '',
      required_skills: '1週間12時間〜の勤務 | その他は学習意欲とやり抜く力があればOK!',
      welcome_skills: '未経験者 経験者優遇',
      promotion_system: '昇給制度：あり',
      remote_policy: '対面勤務',
      selection_flow: '履歴書提出 -> 面接',
      deadline: '',
      welfare_benefits: '',
      apply_url: 'https://tsukubaito.azurewebsites.net/apply/fd1ve/%E3%83%95%E3%83%AA%E3%83%BC%E3%83%80%E3%82%A4%E3%83%96/%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BEFREEDiVE'
    }
    # recruitment_data: {
    #   title: '【成長体験】マーケ力・事業想像力を身につけたい筑波大インターン生WANTED!',
    #   industry: 'マーケティング / 物流 / 業務改善DX',
    #   description: 'FREEDiVEはつくばに拠点を置く8期目のベンチャー企業です。筑波大学のアルバイトインターン/卒業生も含め、多様なバックグラウンドを持つメンバーが集い、4年連続で「ベストベンチャー100」を受賞しました。私たちの特長は、マーケティングノウハウに裏打ちされた「顧客の未来を科学する」アプローチ。データを用いた課題解決を駆使して、常に業界の一歩先を行く戦略を展開しています。3年後の上場に向けて、共に成長していく仲間を募集中です！少しでも興味があれば、ぜひお越しください！',
    #   benefits: '曜日や時間が選べる / 服装自由 / 未経験歓迎 / 経験者優遇 / スキルが身につく / 筑波大生履歴書不要',
    #   job_description: 'コールセンター担当: お客様からのお問い合わせへの対応・アポイントメント取得・資料送付など',
    #   job_titles: 'コールセンター担当',
    #   job_engineer: false,
    #   job_designer: false,
    #   job_sales: false,
    #   job_planning: true,
    #   job_marketing: true,
    #   job_writer: false,
    #   job_others: false,
    #   skills_acquired: '【限定募集】マーケティング・物流・業務改善DXまで多岐に渡ります。\n皆様の希望や面談時の適正に合わせて多種多様なお仕事を経験できます。toCのインバウンド営業やコール業務、企画設計やマーケ、そして業務改善・DX化を進める仕事などがあります。もちろん簡単な軽作業からでもOKです!\n【筑波大生多数所属】過去の経験は問いません！まずは面談からフランクに話しましょう\n筑波大生はインターン/アルバイト含め25名以上在籍!来年卒業を迎える方もいる為、採用強化中です。まずは将来やりたい事や大学生活をお聞きし、当社の説明を聞いていただいた上でマッチすれば面接に進みましょう!\n【時給1200円〜】高時給で様々な経験を得られる良質な長期インターン!\n基本的には週12時間以上の出社を原則としております。もちろん昇給制度もありますので、行う仕事内容や成果に合わせて稼げる!そして社会人に向けての圧倒的な経験を積むことができます。限定10名程度を募集しますよ!',
    #   wage: '時給: 1,300円',
    #   salary_notes: '',
    #   work_location: '茨城県つくば市吾妻1丁目7-1トナリエクレオつくば5F C5030',
    #   min_work_period: '',
    #   min_work_days: '週2回〜',
    #   min_work_hours: '1日あたりの勤務時間は応相談(10:00〜19:00)',
    #   commute_support: '',
    #   required_skills: '1週間12時間〜の勤務 | その他は学習意欲とやり抜く力があればOK!',
    #   welcome_skills: '未経験者 経験者優遇',
    #   promotion_system: '昇給制度：あり',
    #   remote_policy: '対面勤務',
    #   selection_flow: '履歴書提出 -> 面接',
    #   deadline: '',
    #   welfare_benefits: '',
    #   apply_url: 'https://tsukubaito.azurewebsites.net/apply/fd1ve/%E3%83%95%E3%83%AA%E3%83%BC%E3%83%80%E3%82%A4%E3%83%96/%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BEFREEDiVE'
    # },
    # recruitment_data: {
    #   title: '【成長体験】マーケ力・事業想像力を身につけたい筑波大インターン生WANTED!',
    #   industry: 'マーケティング / 物流 / 業務改善DX',
    #   description: 'FREEDiVEはつくばに拠点を置く8期目のベンチャー企業です。筑波大学のアルバイトインターン/卒業生も含め、多様なバックグラウンドを持つメンバーが集い、4年連続で「ベストベンチャー100」を受賞しました。私たちの特長は、マーケティングノウハウに裏打ちされた「顧客の未来を科学する」アプローチ。データを用いた課題解決を駆使して、常に業界の一歩先を行く戦略を展開しています。3年後の上場に向けて、共に成長していく仲間を募集中です!少しでも興味があれば、ぜひお越しください!',
    #   benefits: '曜日や時間が選べる / 服装自由 / 未経験歓迎 / 経験者優遇 / スキルが身につく / 筑波大生履歴書不要',
    #   job_description: '物流サポート担当: モバイルWi-Fiなどの商品の検品等の軽作業',
    #   job_titles: '物流サポート担当',
    #   job_engineer: false,
    #   job_designer: false,
    #   job_sales: false,
    #   job_planning: true,
    #   job_marketing: true,
    #   job_writer: false,
    #   job_others: false,
    #   skills_acquired: '【限定募集】マーケティング・物流・業務改善DXまで多岐に渡ります。\n皆様の希望や面談時の適正に合わせて多種多様なお仕事を経験できます。toCのインバウンド営業やコール業務、企画設計やマーケ、そして業務改善・DX化を進める仕事などがあります。もちろん簡単な軽作業からでもOKです!\n【筑波大生多数所属】過去の経験は問いません！まずは面談からフランクに話しましょう\n筑波大生はインターン/アルバイト含め25名以上在籍!来年卒業を迎える方もいる為、採用強化中です。まずは将来やりたい事や大学生活をお聞きし、当社の説明を聞いていただいた上でマッチすれば面接に進みましょう!\n【時給1200円〜】高時給で様々な経験を得られる良質な長期インターン!\n基本的には週12時間以上の出社を原則としております。もちろん昇給制度もありますので、行う仕事内容や成果に合わせて稼げる!そして社会人に向けての圧倒的な経験を積むことができます。限定10名程度を募集しますよ!',
    #   wage: '時給: 1,200円',
    #   salary_notes: '',
    #   work_location: '茨城県つくば市吾妻1丁目7-1トナリエクレオつくば5F C5030',
    #   min_work_period: '',
    #   min_work_days: '週2回〜',
    #   min_work_hours: '1日あたりの勤務時間は応相談(10:00〜19:00)',
    #   commute_support: '',
    #   required_skills: '1週間12時間〜の勤務 | その他は学習意欲とやり抜く力があればOK!',
    #   welcome_skills: '未経験者 経験者優遇',
    #   promotion_system: '昇給制度：あり',
    #   remote_policy: '対面勤務',
    #   selection_flow: '履歴書提出 -> 面接',
    #   deadline: '',
    #   welfare_benefits: '',
    #   apply_url: 'https://tsukubaito.azurewebsites.net/apply/fd1ve/%E3%83%95%E3%83%AA%E3%83%BC%E3%83%80%E3%82%A4%E3%83%96/%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BEFREEDiVE'
    # }
  }
]

companies.each do |data|
  begin
    company = Company.create!(data[:company_data])
    Recruitment.create!(data[:recruitment_data].merge(company_id: company.id))
  rescue ActiveRecord::RecordInvalid => e
    puts "エラーが発生しました: #{e.record.errors.full_messages.join(', ')}"
  end
end

puts "シードデータの作成が完了しました！"
