Intern.create!(
  [
    {
      nickname: 'S',
      department: 1,
      grade: 3,
      labo: 'Softlab',
      club: '無所属',
      achievements: '26卒Sansan内定',
      experience: 'プログラミング歴1年, Railsを用いた簡単な個人開発',
      company_name: 'Techouse株式会社',
      intern_detail: 'Ruby on Railsを用いた社内プロダクトの保守・運用。機能の要件定義から実装までを行う。社内の勉強会や書籍の購入も自由なので、勉強することが仕事でした。',
      work_duration_description: '学部2年次の冬から',
      weekly_hours_description: '週２日はフルタイム、週１日は４時間。長期休暇期間中は週５フルタイム',
      hourly_wage_description: '研修終了の際に一律3万円。それ以降は、一律で時給1200円',
      work_style: '週２出社、週１リモート。オフィスの近くにインターン生専用の宿があるので、筑波大生はよくそこ泊まって連続で出社しています。',
      application_reason: 'ソフトウェアエンジニアを目指すために、実務経験を積みたいと考えたこと。Web開発未経験からでも挑戦できたこと。',
      acquired_skill: 'Rails を用いた開発経験、毎週開催される社内勉強会で得たコンピュータサイエンスの知識、ソフトウェアエンジニアの仕事の進め方、GitやJiraの使い方など',
      appeal: '週三日稼働できること伝えて、熱量の高さをアピールした',
      advise: '応募時に開発経験がない人がほとんどなので、Web開発未経験からでも挑戦できると感じました。Railsチュートリアルで、Railsの勉強を事前にしておくと研修がスムーズにいきます。',
      evaluation: 5,
      evaluation_reason: '大きなタスクを振ってもらえて、圧倒的に成長することができたから。',
      intern_overview: 'Ruby on Rails を用いた開発',
      catchphrase: 'Sansan26卒内定者',
      hourly_wage: 1200,
      weekly_hours: 21,
      work_duration: 12,
      industry: 1,
      occupation: 2,
      recruitment_id: nil,
    },
    {
      nickname: 'K',
      department: 2,
      grade: 3,
      labo: '融合知能デザイン研究室',
      club: '筑波スマブラサークル',
      achievements: '26卒LINEYahoo内定、26卒DeNA内定',
      experience: 'プログラミング未経験',
      company_name: '株式会社LifeisTech!',
      intern_detail: '中高生にUnityを用いたゲーム開発を指導。ゲーム開発の補助やキャシア相談、動画制作など、幅広く中高生の成長を目的とした業務を行う',
      work_duration_description: '2023/04 ~ 2024/03',
      weekly_hours_description: '週10時間程度',
      hourly_wage_description: '時給1250円',
      work_style: '短期イベントのキャンプでは会場(各大学や高校、企業本社など)に直接、オンラインのプログラムの際はリモート',
      application_reason: '実践的なプログラミングスキルを身につけたいと考えたため、プログラミング未経験からでも挑戦できる環境を求めた',
      acquired_skill: 'プロダクト開発経験、Unityを用いたゲーム開発、中高生向けのプログラミング教育',
      appeal: '新しい技術への好奇心や学意欲をアピール',
      advise: '積極性と教育への思いがあれば、技術力は問われない',
      evaluation: 4,
      evaluation_reason: '中高生の成長を目的とした業務を通じて、技術力だけでなく、コミュニケーションスキル、ファシリテーションスキルなどのソフトスキルの面でも成長できたから。また、東大や京大などの有名大学の学生やAmazonやSONY、LINEYahooの社員さんと一緒に働く機会が多く、多様な価値観やハイレベルな人間関係を築くことができたから。',
      intern_overview: '中高生のプロダクト開発支援',
      catchphrase: 'LINEYahoo26卒内定者！',
      hourly_wage: 1250,
      weekly_hours: 10,
      work_duration: 6,
      industry: 2,
      occupation: 3,
      recruitment_id: nil,
    },
  ]
)

Recruit.create!(
  title: "Ruby on Rails 要件定義から実装まで",
  description: "【実務未経験OK / エンジニア】研修制度・教育支援制度充実！自社プロダクトのWeb開発業務を"PM"として「設計から実装まで」お任せします",
  company_id: 1,
  other_informations: "交通費全額支給／リモートワーク制度あり／服装・髪型自由",
  min_month: "3ヶ月",   # 例: 「最低3ヶ月以上勤務できる方」
  min_days: "週2日",     # 例: 「最低週2日以上勤務できる方」
  min_hours: "週10時間", # 例: 「最低週10時間以上働ける方」
  hourly_wage: 1300,
  salary_notes: "昇給あり。経験・能力を考慮して決定します。",
  work_style: "フレックスタイム制",
  skills_acquired: "Ruby on RailsをはじめとしたWebアプリ開発の基礎／チーム開発の進め方など",
  required_skills: "プログラミング経験(言語不問)、自走力、責任感",
  welcome_skills: "Ruby on Railsでの開発経験、AWSやDockerの知識",
  selection_flow: "書類選考 → 一次面接 → 最終面接 → 内定",
  occupation: "Webエンジニア",
  image1: "sample_image1.png",
  image2: nil,
  image3: nil,  # 空の場合はnilでもOK
  status: true,
)

Company.create!(
  name: "株式会社Techouse",
  description: "人材プラットフォームの提供を主軸に行う企業。国内主要都市に数ヶ所の事業拠点を持ち、人材プラットフォームの提供を行う。主力製品に「クラウドハウス採用」などがある。",
  location: "東京都港区三田3-13-12三田MTビル 5F",
  email: "info@example.co.jp",
  phone_number: "03-1234-5678",
  website_url: "https://jp.techouse.com/",
  logo_url: "",
  picture_url: "",
  industry: "IT・WEB",
  buisness_description: "",
  culture: "",
  appeal: "",
)
