name: Fly Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy backend/ --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Run DB migrations
        run: flyctl ssh console -C "cd backend && bin/rails db:migrate" -a <your-app-name>
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
